<?php
// Automatically Generated by TestLink Installer - Wed, 29 Jul 15 14:17:58 -0300
define('DB_TYPE', 'postgres');
define('DB_USER', 'userteslink');
define('DB_PASS', ']]as+01');
define('DB_HOST', 'www.kmm.com.br');
define('DB_NAME', 'testlink2');
define('DB_TABLE_PREFIX', '');
